# Generated by Django 2.1.3 on 2018-11-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20181128_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oblast',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Country'),
        ),
    ]
