# Generated by Django 2.1.3 on 2018-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20181128_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(help_text='Адрес', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='coordinate',
            field=models.CharField(help_text='Координаты дома(можно посмотреть в google map)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(help_text='почта', max_length=40),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.IntegerField(help_text='ИИН владельца скота', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(help_text='ФИО', max_length=50),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(help_text='номер мобильного'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(help_text='Поселок', on_delete=django.db.models.deletion.CASCADE, to='farmer.Village'),
        ),
    ]
