# Generated by Django 2.1.3 on 2018-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_auto_20181207_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuralDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Сельский округ')),
            ],
            options={
                'verbose_name': 'Сельский округ',
                'verbose_name_plural': 'Сельские округи',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Фермер', 'verbose_name_plural': 'Фермеры'},
        ),
        migrations.AlterModelOptions(
            name='oblast',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': 'Поселки', 'verbose_name_plural': 'Поселок'},
        ),
        migrations.RemoveField(
            model_name='village',
            name='region',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='coordinate',
            field=models.CharField(help_text='Координаты дома(можно посмотреть в google map)', max_length=1000, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Village', verbose_name='Поселок'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер области'),
        ),
        migrations.AlterField(
            model_name='oblast',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='region',
            name='oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Oblast', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Поселок'),
        ),
        migrations.AddField(
            model_name='ruraldistrict',
            name='region',
            field=models.ForeignKey(default='',on_delete=django.db.models.deletion.CASCADE, to='farmer.Region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='village',
            name='ruraldistrict',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmer.RuralDistrict', verbose_name='Сельский округ'),
            preserve_default=False,
        ),
    ]
