# Generated by Django 2.1.3 on 2018-12-08 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20181207_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': '1.Страны'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Фермер', 'verbose_name_plural': '6.Фермеры'},
        ),
        migrations.AlterModelOptions(
            name='oblast',
            options={'verbose_name': 'Область', 'verbose_name_plural': '2.Области'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': '3.Регионы'},
        ),
        migrations.AlterModelOptions(
            name='ruraldistrict',
            options={'verbose_name': 'Сельский округ', 'verbose_name_plural': '4.Сельские округи'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': 'Поселки', 'verbose_name_plural': '5.Поселок'},
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.FloatField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='ruraldistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Region', verbose_name='Регион'),
        ),
    ]
