# Generated by Django 2.1.3 on 2018-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20181208_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False, verbose_name='ИИН'),
        ),
    ]
