# Generated by Django 2.1.3 on 2018-12-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodtest',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Номер теста')),
                ('status', models.BooleanField(help_text='Положительный/Отрицательный', verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Диагно крови',
                'verbose_name_plural': 'Тесты крови',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название болезни', max_length=100, verbose_name='Болезнь')),
            ],
            options={
                'verbose_name': 'Болезнь',
                'verbose_name_plural': 'Болезни',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Номер вакцины')),
                ('name', models.CharField(help_text='название лекарства(если есть одино лекарство,но объем(мл) разный,то нужно вводить каждый)', max_length=100, verbose_name='Вакцина')),
                ('volume', models.IntegerField(help_text='миллилитры(мл)', verbose_name='Объем')),
                ('dose', models.IntegerField(help_text='количество доз на каждый флакон', verbose_name='Доза')),
                ('description', models.CharField(help_text='Описание лекарства(Пропорции на вес,когда лучше ставить,с чем нельзя ставить и т.д)Заметка для вакцинатора', max_length=1000, verbose_name='Описание')),
                ('disease', models.ForeignKey(help_text='Название болезней,которые лечит это лекарство', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Disease', verbose_name='Болезнь')),
            ],
            options={
                'verbose_name': 'Вакцина',
                'verbose_name_plural': 'Вакцины',
            },
        ),
        migrations.CreateModel(
            name='Modeofapplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Способ применения(внутримышечно....)', max_length=100, verbose_name='Способ ввода')),
            ],
            options={
                'verbose_name': 'Ввод препара',
                'verbose_name_plural': 'Способы ввода препарата',
            },
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид исследования')),
            ],
            options={
                'verbose_name': 'Вид Исследования',
                'verbose_name_plural': 'Виды Исследований',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Время, когда поставили вакцину', verbose_name='Дата')),
                ('employee', models.ForeignKey(help_text='Вакцинатор', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Вакцинатор')),
                ('livestock', models.ForeignKey(help_text='Номер животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStock', verbose_name='Животное')),
                ('medicine', models.ForeignKey(help_text='Лекарство', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Medicine', verbose_name='Вакцина')),
            ],
            options={
                'verbose_name': 'Вакцинация',
                'verbose_name_plural': 'Вакцинации',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='modeofapplication',
            field=models.ForeignKey(help_text='Способ применения(внутримышечно....)', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Modeofapplication', verbose_name='Способ ввода'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='typesoflivestock',
            field=models.ForeignKey(help_text='тип животного(у каждого разная доза)', on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock', verbose_name='Тип животного'),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.Disease', verbose_name='Болезнь'),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Вакцинатор'),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='livestock',
            field=models.ForeignKey(help_text='Номер животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStock', verbose_name='Животное'),
        ),
        migrations.AddField(
            model_name='bloodtest',
            name='testmethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.TestMethod', verbose_name='Вид исследования'),
        ),
    ]
