# Generated by Django 2.1.3 on 2018-11-29 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_livestock_age'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose', models.IntegerField()),
                ('disease', models.ManyToManyField(to='vaccination.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bloodtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.Bloodtest')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStock')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination.Medicine')),
            ],
        ),
    ]
