# Generated by Django 2.1.3 on 2018-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20181207_0918'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modeofapplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Способ применения(внутримышечно....)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.CharField(default="Пусто", help_text='Описание лекарства(Пропорции на вес,когда лучше ставить,с чем нельзя ставить и т.д)Заметка для вакцинатора', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='typesoflivestock',
            field=models.ForeignKey(default="", help_text='тип животного(у каждого разная доза)', on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='date',
            field=models.DateField(help_text='дата взятие крови'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='status',
            field=models.BooleanField(help_text='Поставить галочку если тест прошел успешно'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text='название болезни', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ManyToManyField(help_text='Название болезней,которые лечит это лекарство', to='vaccination.Disease'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(help_text='количество доз на каждый флакон'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='название лекарства(если есть одино лекарство,но объем(мл) разный,то нужно вводить каждый)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='bloodtest',
            field=models.ForeignKey(help_text='Тест крови', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Bloodtest'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(help_text='Время, когда поставили вакцину'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='employee',
            field=models.ForeignKey(help_text='Вакцинатор', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='livestock',
            field=models.ForeignKey(help_text='Номер животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStock'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='medicine',
            field=models.ForeignKey(help_text='Лекарство', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='modeofapplication',
            field=models.ForeignKey(default="", help_text='Способ применения(внутримышечно....)', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Modeofapplication'),
            preserve_default=False,
        ),
    ]
