# Generated by Django 2.1.3 on 2019-02-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtest',
            options={'verbose_name': 'Тест крови', 'verbose_name_plural': 'Тесты крови'},
        ),
        migrations.AlterModelOptions(
            name='modeofapplication',
            options={'verbose_name': 'Ввод препарата', 'verbose_name_plural': 'Способы ввода препарата'},
        ),
    ]
