# Generated by Django 2.1.3 on 2019-03-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_auto_20190214_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.Disease', verbose_name='Болезнь'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='status',
            field=models.BooleanField(blank=True, help_text='Положительный/Отрицательный', null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='testmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccination.TestMethod', verbose_name='Вид исследования'),
        ),
    ]
