# Generated by Django 2.1.3 on 2018-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0002_auto_20181207_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodtest',
            options={'verbose_name': 'Тест крови', 'verbose_name_plural': 'Тесты крови'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Болезнь', 'verbose_name_plural': 'Болезни'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Вакцина', 'verbose_name_plural': 'Вакцины'},
        ),
        migrations.AlterModelOptions(
            name='modeofapplication',
            options={'verbose_name': 'Ввод препара', 'verbose_name_plural': 'Способы ввода препарата'},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Вакцинация', 'verbose_name_plural': 'Вакцинации'},
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='date',
            field=models.DateField(help_text='дата взятие крови', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='status',
            field=models.BooleanField(help_text='Поставить галочку если тест прошел успешно', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(help_text='название болезни', max_length=100, verbose_name='Болезнь'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(help_text='Описание лекарства(Пропорции на вес,когда лучше ставить,с чем нельзя ставить и т.д)Заметка для вакцинатора', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='disease',
            field=models.ManyToManyField(help_text='Название болезней,которые лечит это лекарство', to='vaccination.Disease', verbose_name='Болезнь'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(help_text='количество доз на каждый флакон', verbose_name='Доза'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер вакцины'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='modeofapplication',
            field=models.ForeignKey(help_text='Способ применения(внутримышечно....)', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Modeofapplication', verbose_name='Способ ввода'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(help_text='название лекарства(если есть одино лекарство,но объем(мл) разный,то нужно вводить каждый)', max_length=100, verbose_name='Вакцина'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='typesoflivestock',
            field=models.ForeignKey(help_text='тип животного(у каждого разная доза)', on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock', verbose_name='Тип животного'),
        ),
        migrations.AlterField(
            model_name='modeofapplication',
            name='name',
            field=models.CharField(help_text='Способ применения(внутримышечно....)', max_length=100, verbose_name='Способ ввода'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='bloodtest',
            field=models.ForeignKey(help_text='Тест крови', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Bloodtest', verbose_name='Тест крови'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(help_text='Время, когда поставили вакцину', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='employee',
            field=models.ForeignKey(help_text='Вакцинатор', on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='Вакцинатор'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='livestock',
            field=models.ForeignKey(help_text='Номер животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.LiveStock', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='medicine',
            field=models.ForeignKey(help_text='Лекарство', on_delete=django.db.models.deletion.CASCADE, to='vaccination.Medicine', verbose_name='Вакцина'),
        ),
    ]
