# Generated by Django 2.1.3 on 2018-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_auto_20181207_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False, verbose_name='Номер вакцины'),
        ),
    ]
