# Generated by Django 2.1.3 on 2018-12-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Отдела')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('coordinate', models.CharField(blank=True, help_text='Координаты отдела(можно найти через google maps) Выглядит так 43.202556, 76.632247', max_length=1000, null=True, verbose_name='Координаты')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ИИН работника')),
                ('employeeskey', models.CharField(max_length=1000, verbose_name='Пароль')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Тип работника',
                'verbose_name_plural': 'Типы работников',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeType', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ruraldistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.RuralDistrict', verbose_name='Сельский округ'),
        ),
    ]
