# Generated by Django 2.1.3 on 2018-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(help_text='Адресс отдела', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='coordinate',
            field=models.CharField(help_text='Координаты отдела(можно найти через google maps) Выглядит так 43.202556, 76.632247', max_length=1000),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Название Отдела', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='village',
            field=models.ForeignKey(help_text='Поселок', on_delete=django.db.models.deletion.CASCADE, to='farmer.Village'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(help_text='Отдел', on_delete=django.db.models.deletion.CASCADE, to='employee.Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeskey',
            field=models.CharField(help_text='Пароль', max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.ForeignKey(help_text='Тип работника', on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeType'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(help_text='ИИН работника', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='ФИО', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='name',
            field=models.CharField(help_text='Тип работника', max_length=100),
        ),
    ]
