# Generated by Django 2.1.3 on 2018-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20181207_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='department',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='department',
            name='coordinate',
            field=models.CharField(help_text='Координаты отдела(можно найти через google maps) Выглядит так 43.202556, 76.632247', max_length=1000, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название Отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Village', verbose_name='Поселок'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeskey',
            field=models.CharField(help_text='Пароль', max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeType', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ИИН работника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
    ]
