# Generated by Django 2.1.3 on 2018-12-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20181207_1615'),
        ('employee', '0003_auto_20181207_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetype',
            options={'verbose_name': 'Специальность', 'verbose_name_plural': 'Специальности'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='village',
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmer.Region', verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Специальность'),
        ),
    ]
