# Generated by Django 2.1.3 on 2018-12-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181207_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetype',
            options={'verbose_name': 'Тип работника', 'verbose_name_plural': 'Типы работников'},
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.FloatField(default=1, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
