# Generated by Django 2.1.3 on 2018-12-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20181208_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeskey',
            field=models.CharField(max_length=1000, verbose_name='Пароль'),
        ),
    ]
