# Generated by Django 2.1.3 on 2018-12-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20181209_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ИИН работника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
