# Generated by Django 2.1.3 on 2018-12-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20181209_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='coordinate',
            field=models.CharField(help_text='Координаты отдела(можно найти через google maps) Выглядит так 43.202556, 76.632247', max_length=1000, null=True, verbose_name='Координаты'),
        ),
    ]
