# Generated by Django 2.1.3 on 2018-12-14 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_auto_20181211_1154'),
        ('employee', '0010_auto_20181211_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ruraldistrict',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farmer.RuralDistrict', verbose_name='Сельский округ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeskey',
            field=models.IntegerField(max_length=1000, verbose_name='Пароль'),
        ),
    ]
