# Generated by Django 2.1.3 on 2018-11-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0003_auto_20181128_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypesofLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Suit')),
            ],
        ),
        migrations.AddField(
            model_name='livestock',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Sex'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='typeoflivestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock'),
        ),
    ]
