# Generated by Django 2.1.3 on 2018-12-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStock',
            fields=[
                ('id', models.CharField(help_text='KZB212345678', max_length=100, primary_key=True, serialize=False, verbose_name='Номер животного')),
                ('age', models.IntegerField(verbose_name='Месяцы')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer', verbose_name='ИИН Владельца животного')),
                ('placeofbirth', models.ForeignKey(help_text='Поселок,где родилось животное', on_delete=django.db.models.deletion.CASCADE, to='farmer.Village', verbose_name='Населенный пункт')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Масть животного/Порода')),
            ],
            options={
                'verbose_name': 'Масть',
                'verbose_name_plural': 'Масти',
            },
        ),
        migrations.CreateModel(
            name='TypesofLiveStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='тип скота(крупнорогатый,лошади,верблюды)', max_length=100, verbose_name='Тип животного')),
                ('suit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Suit', verbose_name='Масть животного')),
            ],
            options={
                'verbose_name': 'Тип животного',
                'verbose_name_plural': 'Типы животного',
            },
        ),
        migrations.AddField(
            model_name='livestock',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Sex', verbose_name='Пол животного'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='typeoflivestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock', verbose_name='Тип Животного'),
        ),
    ]
