# Generated by Django 2.1.3 on 2018-11-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
