# Generated by Django 2.1.3 on 2019-02-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typesoflivestock',
            options={'verbose_name': 'Вид животного', 'verbose_name_plural': 'Виды животных'},
        ),
        migrations.AlterField(
            model_name='livestock',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to='farmer.Farmer', verbose_name='ИИН Владельца животного'),
        ),
        migrations.AlterField(
            model_name='typesoflivestock',
            name='name',
            field=models.CharField(help_text='вид скота(крупнорогатый,лошади,верблюды)', max_length=100, verbose_name='Вид животного'),
        ),
    ]
