# Generated by Django 2.1.3 on 2018-12-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_auto_20181207_0918'),
        ('livestock', '0002_livestock_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='placeofbirth',
            field=models.ForeignKey(default="", help_text='Поселок,где родилось животное', on_delete=django.db.models.deletion.CASCADE, to='farmer.Village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.IntegerField(help_text='Лет'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='farmer',
            field=models.ForeignKey(help_text='ИИН фермера', on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='sex',
            field=models.ForeignKey(help_text='Пол животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.Sex'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='typeoflivestock',
            field=models.ForeignKey(help_text='Тип скота', on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(help_text='Род животного', max_length=20),
        ),
        migrations.AlterField(
            model_name='suit',
            name='name',
            field=models.CharField(help_text='название масти животного', max_length=100),
        ),
        migrations.AlterField(
            model_name='typesoflivestock',
            name='name',
            field=models.CharField(help_text='тип скота(крупнорогатый,лошади,верблюды)', max_length=100),
        ),
        migrations.AlterField(
            model_name='typesoflivestock',
            name='suit',
            field=models.ForeignKey(help_text='Масть животного', on_delete=django.db.models.deletion.CASCADE, to='livestock.Suit'),
        ),
    ]
