# Generated by Django 2.1.3 on 2018-12-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20181207_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestock',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Пол', 'verbose_name_plural': 'Полы'},
        ),
        migrations.AlterModelOptions(
            name='suit',
            options={'verbose_name': 'Масть', 'verbose_name_plural': 'Масти'},
        ),
        migrations.AlterModelOptions(
            name='typesoflivestock',
            options={'verbose_name': 'Тип животного', 'verbose_name_plural': 'Типы животного'},
        ),
        migrations.AlterField(
            model_name='livestock',
            name='age',
            field=models.IntegerField(verbose_name='Лет'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.Farmer', verbose_name='ИИН фермера'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.IntegerField(help_text='8 цифр', primary_key=True, serialize=False, verbose_name='Номер животного'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='placeofbirth',
            field=models.ForeignKey(help_text='Поселок,где родилось животное', on_delete=django.db.models.deletion.CASCADE, to='farmer.Village', verbose_name='Поселок'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Sex', verbose_name='Пол животного'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='typeoflivestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.TypesofLiveStock', verbose_name='Тип скота'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='suit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Масть животного/Порода'),
        ),
        migrations.AlterField(
            model_name='typesoflivestock',
            name='name',
            field=models.CharField(help_text='тип скота(крупнорогатый,лошади,верблюды)', max_length=100, verbose_name='Тип животного'),
        ),
        migrations.AlterField(
            model_name='typesoflivestock',
            name='suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.Suit', verbose_name='Масть животного'),
        ),
    ]
