# Generated by Django 2.1.3 on 2018-12-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20181207_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.FloatField(help_text='8 цифр', primary_key=True, serialize=False, verbose_name='Номер животного'),
        ),
    ]
