# Generated by Django 2.1.3 on 2018-12-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20181208_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.CharField(help_text='8 цифр', max_length=100, primary_key=True, serialize=False, verbose_name='Номер животного'),
        ),
    ]
